# Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2. The first ten
#  pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their difference,
#   70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and
#  difference are pentagonal and D = |P(k) − P(j)| is minimised; what is the value of D?
# Time to complete: 15 minutes

def pentagonal(num)
  num * (3 * num - 1) / 2
end

MAX_PENTAGONALS = 10000 # a guess

pentagonals = [0]
pentagonal_map = {}
(1..MAX_PENTAGONALS).each.with_index do |num, idx|
  value = pentagonal(num)
  pentagonals << value
  pentagonal_map[value] = 1
end

pairs = []
pentagonals.drop(1).each do |j|
  pentagonals.drop(1).each do |k|
    if pentagonal_map[j + k] && pentagonal_map[k - j]
      pairs << (k - j).abs
    end
  end
end

p pairs
