# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# Time to complete: 5 minutes

fib = [1, 2, 3]
even_fib_sum = 2
max_fib = 4_000_000
while fib.last < max_fib
  next_fib = fib[-1] + fib[-2]
  even_fib_sum += next_fib if next_fib % 2 == 0
  fib << next_fib
end

p even_fib_sum
